ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'POS';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_method VARCHAR(20) DEFAULT 'COLLECTION';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paynow_reference VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paynow_poll_url VARCHAR(500);
